### ISSUE TITLE
confusion about comment for ndcg

### ISSUE THREAD

**Issue by we1559** [HarrieO/2021-SIGIR-plackett-luce#1]
hi, I'm confused aboud the code below
https://github.com/HarrieO/2021-SIGIR-plackett-luce/blob/8a59cdfe565e59e6f122ddd6dc807ee156d25b8c/run.py#L132

it says we should uncomment it for NDCG, but it says we could use command

> python3` run.py local_output/yahoo_ndcg5_dynamic_plrank2.txt --num_samples dynamic --loss PL_rank_2 --cutoff 5 --dataset `Webscope_C14_Set1

to optimize NDCG@5 withoud any change to run.py

Is it by design or there is a bug here?

**Comment by HarrieO** [comment]
Thanks for pointing this out!

The readme is incorrect as the command optimizes DCG@5 instead of NDCG@5; to optimize NDCG@5 you indeed have to change the run.py file.
