### ISSUE TITLE
Confusion about data set source file format

### ISSUE THREAD

**Issue by AndyZZt** [HarrieO/2021-SIGIR-plackett-luce#2]
I read the code details and noticed that the code directly read .json files, but the official download link of these data sets are all .txt files. Politely, I wonder if you have cleaned source data or changed the format by yourself? Or it's just because I didn't find the right download link for data sets?

**Comment by HarrieO** [comment]
The code will clean and pre-process the files for you, so it does take in the .txt files.

How it works is that you have to provide a json file that provides information about the datasets, if you start with the example file: 'example_datasets_info.txt' you only have to change the paths in that file: i.e. change "/PATH/TO/MSLR-WEB30k/Fold1/" to the  path of the folder in which the train.txt vali.txt and test.txt files for the MSLR dataset are stored.

Then the --dataset_info_path flag should link to the json file and in turn the json file provides the paths to the txt files.
