### ISSUE TITLE
reproduce results in Fig. 3

### ISSUE THREAD

**Issue by rguo12** [HarrieO/2021-SIGIR-plackett-luce#4]
Hi Harrie,

I am trying to reproduce the results in Fig. 3 of your SIGIR'21 paper but I cannot find the best hyperparameters of each algorithm that achieves the performance reported in Fig. 3. I wonder if you could kindly share them.

Best,

Ruocheng

**Comment by HarrieO** [comment]
Hi Roucheng,

Have you tried running fairrun.py and with the following flag? --num_samples dynamic

Best,
Harrie

**Comment by rguo12** [comment]
Thanks, with that setting, I was able to reproduce the value of the disparity measure used in the paper.
